artifact_uri: file:///Users/zhanghq/Learning/ml_workflow/mlrun/382898302266924594/d7720314df1149f3a3aacfab02bfad19/artifacts
end_time: 1721280783310
entry_point_name: ''
experiment_id: '382898302266924594'
lifecycle_stage: active
run_id: d7720314df1149f3a3aacfab02bfad19
run_name: 'RandomForest_{''n_estimators'': 50, ''max_depth'': 10, ''n_jobs'': 6}'
run_uuid: d7720314df1149f3a3aacfab02bfad19
source_name: ''
source_type: 4
source_version: ''
start_time: 1721280780657
status: 3
tags: []
user_id: zhanghq
